                <input type="hidden" name="version" value="2.2" />
                <input type="hidden" name="start" value="0" />
                <input type="hidden" name="qt" value="standard" />
                <input type="hidden" name="wt" value="phps" />
                <input type="hidden" name="indent" value="on" />
                <input type="hidden" name="facet" value="true" />
                <input type="hidden" name="facet.field1" value="genreform1" />
		<input type="hidden" name="facet.field2" value="folder_num" />
		<input type="hidden" name="facet.field3" value="file_unittitle" />
                <input type="hidden" name="facet.mincount" value="1" />
		<input type="hidden" name="f.file_unittitle.facet.limit" value="-1" />
                <input type="hidden" name="h1" value="on" />
                <input type="hidden" name="h1.f1" value="ocr" />
		<input type="hidden" name="fragsize" value="50" /> 
                <input type="hidden" name="f1" value="*,score" />
                <input type="hidden" name="snippets" value="5" />
